### PR TITLE
Add local caching option using BiocFileCache 

### PR DESCRIPTION
**Pull request by deepayan**
This allows the option of caching downloaded files using the BiocFileCache package. As this is much more well tested, the patch also removes the earlier 'local mirror' option.

### CODE REVIEW

**Comment by cjendres1** [comment]
**BiocFileCache** is not on CRAN. Not sure I could submit nhanesA to CRAN with such a dependency. Is there a CRAN-friendly alternative? Haven't worked with these but they seem popular: [cachem](https://cran.r-project.org/web/packages/cachem/index.html), [R.cache](https://cran.r-project.org/web/packages/R.cache/index.html)

**Comment by deepayan** [comment]
Depending on BioC packages is OK for CRAN packages; basically anything available here should be OK:

```
> tools:::.get_standard_repository_URLs()
                                                    CRAN 
                            "https://CRAN.R-project.org" 
                                                BioCsoft 
           "https://bioconductor.org/packages/3.18/bioc" 
                                                 BioCann 
"https://bioconductor.org/packages/3.18/data/annotation" 
                                                 BioCexp 
"https://bioconductor.org/packages/3.18/data/experiment" 
```

But let me check on the other options first.

**Comment by deepayan** [comment]
Both cachem and R.cache are for cacheing objects, whereas BiocFileCache is for cacheing files. 

cachem doesn't seem particularly suited to our use case. R.cache could be useful, in the sense that it caches results of function calls tagged by arguments, so that 

nhanes("DEMO_J")

could cache its result so that subsequent calls (with exactly the same arguments) would just retrieve the cached result. This would actually be quite nice, because it would avoid repeating even the read.xport() calls.

The problem that I see with this is that it doesn't keep track of whether the source file has changed. That probably doesn't happen very often, but CDC does keep updating their files. Currently,

```
> xtabs(~ startsWith(Date.Published, "Updated"), nhanesManifest())
startsWith(Date.Published, "Updated")
FALSE  TRUE 
 1101   412 
```

so more than 25% of the files have been updated after release. I think BiocFileCache() is supposed to keep track of that and redownload if a new copy is available. At least it keeps track of the last-modified time:

```
> head(bfcinfo(BiocFileCache()), 8) |> with(data.frame(URL = substring(rname, 34, 60), create_time, last_modified_time))
                          URL         create_time  last_modified_time
1         2007-2008/BPX_E.XPT 2023-11-12 19:55:07 2014-05-22 14:38:27
2         2007-2008/BPX_E.htm 2023-11-12 19:55:09 2018-01-19 15:14:31
3      2009-2010/FOLATE_F.XPT 2023-11-12 19:55:09 2014-05-22 14:39:08
4      2009-2010/FOLATE_F.htm 2023-11-12 19:55:10 2019-02-28 13:56:57
5         2005-2006/AUX_D.htm 2023-11-12 19:55:11 2018-01-19 15:16:07
6         2017-2018/BPX_J.htm 2023-11-12 19:55:11 2020-02-18 13:16:54
7        search/DataPage.aspx 2023-11-12 19:55:32                <NA>
8 search/variablelist.aspx?Co 2023-11-12 19:55:34                <NA>

```
 
and for e.g. the first one, this matches the headers:

```
> curlGetHeaders("https://wwwn.cdc.gov/nchs/nhanes/2007-2008/BPX_E.XPT") |> substring(1, 50)
 [1] "HTTP/1.1 200 OK\r\n"                                
 [2] "Cache-Control: no-store, no-cache, must-revalidate" 
 [3] "Pragma: no-cache\r\n"                               
 [4] "Content-Length: 2113200\r\n"                        
 [5] "Content-Type: application/octet-stream\r\n"         
 [6] "Expires: 0\r\n"                                     
 [7] "Last-Modified: Thu, 22 May 2014 14:38:27 GMT\r\n"   
 [8] "Accept-Ranges: bytes\r\n"                           
 [9] "ETag: \"5d537ecb75cf1:0\"\r\n"                      
[10] "X-UA-Compatible: IE=Edge\r\n"                       
[11] "Content-Security-Policy: frame-ancestors 'self'\r\n"
[12] "Strict-Transport-Security: max-age=315360000\r\n"   
[13] "X-Content-Type-Options: nosniff\r\n"                
[14] "X-Frame-Options: SAMEORIGIN\r\n"                    
[15] "X-XSS-Protection: 1; mode=block\r\n"                
[16] "Date: Tue, 14 Nov 2023 14:25:17 GMT\r\n"            
[17] "Set-Cookie: TS01ae363a=015d0abe872fe0c06f8d2c63ead" 
[18] "\r\n"                                               
attr(,"status")
[1] 200
```

**Comment by cjendres1** [comment]
There's also this: https://cran.r-project.org/web/packages/pkgfilecache/index.html

Since file cache is more relevant to Docker, I'd like Robert to weigh in and see if he agrees with this solution. It's a nice feature, but I'd feel more comfortable with a second opinion.

**Comment by deepayan** [comment]
Sure. But just to be clear, the file cacheing is not relevant to docker, quite the opposite in fact. A user running docker will be using the database, so will not download anything from the NHANES website. On the other hand, someone using nhanesA normally outside docker will be downloading the relevant XPT or HTML file every time `nhanes()` or `nhanesCodebook()` is called. If cacheing is enabled, there will be only one download per file (unless the file is updated).

But if you have doubts, I think it's best to discuss them in a call with Robert.

**Comment by cjendres1** [comment]
In that case I don't see the purpose of file caching. I thought it was a way to ensure the Docker files are up to date. 
Outside of Docker, file import from NHANES is the desired behavior. It seems like wasted effort to check for updates when you can simply import the current data, which are mostly small tables. I feel that caching is targeted to a rare use case where a user maintains their own NHANES database and frequently runs a script against a large volume of NHANES tables. That use case is addressed by Docker.

**Comment by deepayan** [comment]
Well, the cost of bandwidth can be different for different users, but I see your point. If we don't want to complicate nhanesA, it should still be possible to make the caching mechanism available as a separate package for those who might find it useful. Anyway, let's wait for Robert's input.

**Pull request closed without merging**
